### ISSUE TITLE
login button not visible in Firefox

### ISSUE THREAD

**Issue by wittigue** [BioComputingUP/apicuron-issues#2]
**Describe the bug**
Login button in the menu bar not visible in Firefox browser

**Desktop (please complete the following information):**
Firefox version 119.0

**Comment by adelbke** [comment]
I didn't manage to reproduce the issue on firefox.

I managed to reproduce the disappearance of the login button on Chrome.
When I attempted to login it worked as it did on Chrome.

This should be fixed now.

**Comment by wittigue** [comment]
Now it works, thanks.
